### ISSUE TITLE
Hyperparameters to reproduce results

### ISSUE THREAD

**Issue by neerajgangwar** [scale-lab/MTLoRA#4]
Hi!
I am working on reproducing the results presented in Table 1 of your paper using this codebase. I have a couple of questions and was hoping you could help me with those:

1. I am using the command mentioned in the README file with a batch size of 16 and have removed the epochs argument (which should run the training for 300 epochs). The config and Swin checkpoint used are `mtlora_tiny_448_r64_scale4_pertask` from the config directory and the Swin-T V1 ImageNet-1k (the first row in "ImageNet-1K and ImageNet-22K Pretrained Swin-V1 Models" from https://github.com/microsoft/Swin-Transformer), respectively. Could you please confirm if these values are correct for reproducing the results in Table 1 or if I need to change any other hyperparameters?
2. Did you use one V100 GPU for your experiments? If so, were you able to increase the batch size beyond 16? I am asking because the default value of the batch size is 128.
3. To reproduce other results in the paper, can I used the same hyperparameters as mentioned above?

It would be great if you can help with the above queries.

Thanks!
Neeraj

**Comment by ahmed-agiza** [comment]
Hi @neerajgangwar,
1) Everything you mentioned is correct, except that we used a batch size of 32. I can also try to locate the weight file if you just want to evaluate.
2) We used a batch size of 32 as I mentioned, on a single V100 (and few experiments used A40 when V100s weren't available), I think we couldn't fit 64 iirc; but be careful because following Swin's codebase, the base LR is scaled with the batch size, so not sure if this _may_ affect the results but things didn't seem sensitive to the LR in our exeperiments.
3) Yes, if you use the same batch size/configuration file/300 epcohs/same swin checkpoints..etc, you should be able to reproduce the results.

**Comment by neerajgangwar** [comment]
Hi @ahmed-agiza,

Thanks for the clarifications. I have a couple of followups:

1. It would be great if you could share the checkpoints. Also, how did you select the best model among all the checkpoints? And are the results presented on the validation set of PASCAL-MT?
2. When I use `python main.py`, it fails with `ValueError: Error initializing torch.distributed` because of [main.py#L559](https://github.com/scale-lab/MTLoRA/blob/9c64503748f2a7565a29d04139f709e6837040e1/main.py#L559). So instead, I am using `torchrun`. Could you please check if this is the right way to invoke the script or am I missing something?
3. If I use a batch size of 32 on a single V100 (16GB memory), the model fails with the out-of-memory error. I am not sure if this is because the `torchrun` command mentioned above or if you used a 32GB version of V100. Could you confirm these?

**Comment by ahmed-agiza** [comment]
1) Sure, I will try to locate it, but probably it will be sometime after the conference because of some logistics; I may retrain it again if I couldn't reach it. And yes, the results are on the **validation set of PASCAL-MT**.
2) I will look into this issue, but till I fix it, you should be able to run it through `python -m torch.distributed.launch --nproc_per_node 1 --master_port 12345 main.py <rest of the arguments>`
3) Yes, our V100 are all 32GB (and as I mentioned, some experiments may have been scheduled on A40).

**Comment by neerajgangwar** [comment]
Great, thank you very much for clarifications. Appreciate your prompt responses!
