### ISSUE TITLE
Baseline related questions

### ISSUE THREAD

**Issue by neerajgangwar** [scale-lab/MTLoRA#8]
Hi @ahmed-agiza,

I have a question about the baselines mentioned in the paper. In the LoRA baseline, is it just one LoRA module in each attention layer which is shared among tasks?

Also, did you experiment with having only task-specific modules in all stages and transformer blocks. This means no parameter sharing among tasks at any stage. If so, what were your findings?

Thanks!

**Comment by ahmed-agiza** [comment]
Hi @neerajgangwar, for the LoRA part, I don't remember 100% since it was very early in the project but most likely yes.

For the second part, if you mean to use TS-LoRA across all the modules, we didn't want to do that cause it will end up causing branches across the whole forward pass so you will be pretty much executing the model multiple times just like single task, but in theory it should be the same as fine-tuning a single task model for each task.

**Comment by neerajgangwar** [comment]
Thanks for the information! @ahmed-agiza

**Comment by neerajgangwar** [comment]
Hi @ahmed-agiza!

I have a follow-up on the LoRA baseline. I am not able to match the number of parameters mentioned for LoRA in Table 1. I tried adding LoRA layers with a rank of 4 in QKV only and QKV + Projection layers. Could you please help with the configuration that you used in your experiments?

Also, for BitFit, I get approximately the number mentioned in the paper if I filter the parameters with `bias` in their names. However, this includes parameters for position bias (`relative_position_bias_table` in the names). I am not sure if this is how the number was computed or if I am missing something.

There seems to be a mismatch in "MTL - Full Fine Tuning" also. I tried running the code with `configs/swin/swin_tiny_patch4_window7_448.yaml` which prints the total number of parameters as 29.4M. This number is correct for "MTL - Tuning Decoders Only", which I am reproducing using `--freeze-backbone` option, and I get ~1.946M parameters.

I would appreciate it if you could clarify the number of trainable parameters mentioned in Table 1 of the paper.

Thanks!

**Comment by ahmed-agiza** [comment]
Hi @neerajgangwar, I don't know why I didn't see the notification for the issue!

Unfortunately, the baselines were mostly handled by my co-author, so honestly, I cannot help much with this part.

For the second part, I would rely on the numbers in the **codebase**  (since it is a minor discrepancy and I don't think I will have time soon to investigate this part soon) and the results  are pretty close.
Also, I retrained the model as promised and posted the weights, so feel free to use the pretrained model since its numbers are a bit closer to the paper.

**Comment by neerajgangwar** [comment]
Thanks @ahmed-agiza!
